CREATE TABLE IF NOT EXISTS file (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    location TEXT NOT NULL UNIQUE CHECK(LENGTH(TRIM(location)) > 0)
);

CREATE TABLE IF NOT EXISTS collection (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL UNIQUE CHECK(LENGTH(TRIM(name)) > 0),
    description TEXT
);

CREATE TABLE IF NOT EXISTS workspace (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL UNIQUE CHECK(LENGTH(TRIM(name)) > 0),
    branch TEXT UNIQUE,
    description TEXT,
    creation TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file_collection (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    id_file INTEGER NOT NULL,
    id_collection INTEGER NOT NULL,
    FOREIGN KEY (id_file) REFERENCES file(id) ON DELETE CASCADE,
    FOREIGN KEY (id_collection) REFERENCES collection(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS collection_workspace (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    id_collection INTEGER NOT NULL,
    id_workspace INTEGER NOT NULL,
    FOREIGN KEY (id_collection) REFERENCES collection(id) ON DELETE CASCADE,
    FOREIGN KEY (id_workspace) REFERENCES workspace(id) ON DELETE CASCADE
);

